# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-23 18:34
from __future__ import unicode_literals
import re

from django.db import migrations
from django.db.models.expressions import RawSQL

from osf.utils.migrations import disable_auto_now_fields

def noop(*args, **kwargs):
    pass

def clean_reg_meta(apps, schema):
    Registration = apps.get_model('osf', 'registration')
    targets = Registration.objects.annotate(
        ml=RawSQL('SELECT count(*) FROM (SELECT jsonb_object_keys(registered_meta)) jsonbob', [])
    ).filter(ml__gt=1).exclude(
        id__in=RawSQL(re.sub(r'\s+', ' ', """
            SELECT abstractnode_id nid
            FROM osf_abstractnode_registered_schema
            GROUP BY abstractnode_id
              HAVING COUNT(abstractnode_id) > 1
            """), []
        )
    )
    with disable_auto_now_fields(models=[Registration]):
        for target in targets:
            assert target.registered_schema.count() == 1
            for schema_id in list(target.registered_meta.keys()):
                if schema_id != target.registered_schema.first()._id:
                    target.registered_meta.pop(schema_id)
            target.save()

class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0154_merge_20190109_1554'),
    ]

    operations = [
        migrations.RunPython(clean_reg_meta, noop)
    ]
